initialized ansible-role-portainer-agent

diff --git a/.github/workflows/daily-e2e-test.yml b/.github/workflows/daily-e2e-test.yml
--- a/.github/workflows/daily-e2e-test.yml
+++ b/.github/workflows/daily-e2e-test.yml
@@ -72,36 +72,36 @@ jobs:
         run: ansible-playbook -i inventory.yml playbook-linux-podman.yml --connection=local
 
       # ───── Kubernetes ─────
-      - name: Install kubectl
-        run: make install-kubectl
+   #   - name: Install kubectl
+   #     run: make install-kubectl
 
-      - name: Install k3d
-        run: make install-k3d
+   #   - name: Install k3d
+   #     run: make install-k3d
 
-      - name: Create k3d cluster
-        run: k3d cluster create portainer-test --wait
+   #   - name: Create k3d cluster
+   #     run: k3d cluster create portainer-test --wait
 
-      - name: Set KUBECONFIG env var
-        run: echo "KUBECONFIG=$(k3d kubeconfig write portainer-test)" >> $GITHUB_ENV
+   #   - name: Set KUBECONFIG env var
+   #     run: echo "KUBECONFIG=$(k3d kubeconfig write portainer-test)" >> $GITHUB_ENV
 
-      - name: Wait for Kubernetes API server
-        run: |
-          RETRIES=20
-          for i in $(seq 1 $RETRIES); do
-            if kubectl cluster-info > /dev/null 2>&1; then
-              echo "✅ Kubernetes API is available."
-              exit 0
-            fi
-            echo "⏳ Waiting for Kubernetes API to be ready ($i/$RETRIES)..."
-            sleep 5
-           done
-          echo "❌ Kubernetes API did not become available in time."
-          exit 1
+   #   - name: Wait for Kubernetes API server
+   #     run: |
+   #       RETRIES=20
+   #       for i in $(seq 1 $RETRIES); do
+   #         if kubectl cluster-info > /dev/null 2>&1; then
+   #           echo "✅ Kubernetes API is available."
+   #           exit 0
+   #         fi
+   #         echo "⏳ Waiting for Kubernetes API to be ready ($i/$RETRIES)..."
+   #         sleep 5
+   #        done
+   #       echo "❌ Kubernetes API did not become available in time."
+   #       exit 1
 
-      - name: Run Kubernetes playbook
-        run: ansible-playbook -i inventory.yml playbook-linux-k8s-lb.yml --connection=local
+   #   - name: Run Kubernetes playbook
+   #     run: ansible-playbook -i inventory.yml playbook-linux-k8s-lb.yml --connection=local
 
-      - name: Verify Portainer Agent pod is running
-        run: |
-          kubectl get pods -n portainer
-          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=portainer-agent -n portainer --timeout=60s
+   #   - name: Verify Portainer Agent pod is running
+   #     run: |
+   #       kubectl get pods -n portainer
+   #       kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=portainer-agent -n portainer --timeout=60s
